import '@/assets/styles/main.scss';
import type { Metadata } from 'next';
import { montserrat } from '@/lib/fonts';
import Navbar from '@/components/Navbar';
import { ReduxProvider } from './StoreProvider';

export const metadata: Metadata = {
	title: 'Portfolio RoldDev',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${montserrat.className} p-5 lg:p-10`}>
				<ReduxProvider>
					<Navbar />
					{children}
				</ReduxProvider>
			</body>
		</html>
	);
}
