import '@/assets/styles/main.scss';
import type { Metadata } from 'next';
import { montserrat } from '@/lib/fonts';
import Navbar from '@/components/Header/Navbar';
import Footer from '@/components/Header/Footer';

import { ReduxProvider } from './StoreProvider';
import Providers from './Providers';

export const metadata: Metadata = {
	title: 'RoldDev | Portfolio',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={montserrat.className}>
				<ReduxProvider>
					<Providers>
						<Navbar />
						{children}
						<Footer />
					</Providers>
				</ReduxProvider>
			</body>
		</html>
	);
}
